zookeeper:
  url: 192.168.123.100:2181
  timeout: 8000
  test:
    path: /justfortest
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apicollection?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.web: debug
    com.ashzd.apiplatform: debug
    org.springframework.boot.autoconfigure: error
  file:
    path: logs/
debug: true