zookeeper:
  url: 192.168.123.100:2181
  timeout: 10000
  test:
    path: /justfortest

apicollection:
  ip: 192.168.123.186
  port: 8080
  service:
    name: test
  swagger:
    packagePath: com.ashzd.apicollectionsdk.test
    docTitle: apicollectionsdk
    docDescription: apicollectionsdk doc
    docDeployUrl: localhost:8080/
    contactName: test doc
    contactUrl: localhost:8080/swagger-ui.html
    contactEmail: ash_zd@qq.com
    docVersion: 1.0 Beta

