mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.ashzd.seckill.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  profiles:
    active: @profiles.active@
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/seckill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    database: 0
    #    host: 192.168.123.100
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100
    pool:
      max-active: 1000
      max-wait: 500
      max-idle: 1000

debug: true

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.web: debug
    com.ashzd.seckill: debug
